#include "param.h"
#include "types.h"
#include "atomic.h"
#include "memlayout.h"
#include "elf.h"
#include "riscv.h"
#include "defs.h"
#include "spinlock.h"
#include "proc.h"
#include "fs.h"
#include "sleeplock.h"
#include "file.h"
#include "fcntl.h"
#include "rbtree.h"
#include "kvm.h"
#include "mm.h"
#include "vm.h"
#include "vm_internal.h"
#include "colors.h"
#include "utils.h"

//VMA. address space metadata.